# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161120_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='just_test',
            field=models.CharField(max_length=120, verbose_name='用于测试'),
        ),
    ]
