# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 13:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20161120_2158'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('other_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
